# Generated by Django 3.1.4 on 2021-01-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShutdownValve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_four', models.FloatField(verbose_name='Station 4')),
                ('station_five', models.FloatField(verbose_name='Station 5')),
                ('station_six', models.FloatField(verbose_name='Station 6')),
                ('valve', models.FloatField(verbose_name='Shutdown Valve')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
        ),
    ]
