# Generated by Django 3.1.4 on 2021-01-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210105_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdownvalve',
            name='station_five',
            field=models.FloatField(blank=True, null=True, verbose_name='Station 5'),
        ),
        migrations.AlterField(
            model_name='shutdownvalve',
            name='station_six',
            field=models.FloatField(blank=True, null=True, verbose_name='Station 6'),
        ),
    ]
